Update pay_via_payment_details.d.ts
alexbosworth/lightning pull request #67
Opened 2022-03-21 08:31 UTC by apotdevin

I think `routes` is optional but not totally sure about this

2022-03-21 15:18 UTC, alexbosworth approved these changes

2022-03-22 18:15 UTC, bkiac commented
Type test fails because it expects `routes` to be required instead of optional. I'm not familiar with the method, so I can't judge if `routes` should be optional or not; if it should be, in fact, optional, the test should be updated too.

2022-03-22 18:23 UTC, alexbosworth commented
Yes it should be optional, this is a docs bug

Routes here refers to hop hint paths to take, for non private requests they are not required

2022-03-22 18:23 UTC, alexbosworth requested changes
Please fix test

2022-03-23 15:04 UTC, merged